title: k-nut.eu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://k-nut.eu"
twitter:
 username: notknut

# Build settings
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false

exclude:
 - Gemfile
 - Gemfile.lock
 - deploy.sh
 - vendor

include:
  - .well-known

plugins:
 - jekyll-seo-tag
